stages:
  - build
  - push
  - deploy

image: docker:latest

services:
  - docker:dind

build_mysql_image:
  stage: build
  script:
    - export CI_IMAGE_NAMESPACE=georgi.heroco
    - docker login -u $CI_USER -p $CI_PASSWORD $CI_HOST
    - docker build -t $CI_IMAGE_NAMESPACE/my-db:$CI_COMMIT_SHORT_SHA ./db/
    - docker tag $CI_IMAGE_NAMESPACE/my-db:$CI_COMMIT_SHORT_SHA $CI_IMAGE_NAMESPACE/my-db:latest
    - docker push $CI_IMAGE_NAMESPACE/my-db:$CI_COMMIT_SHORT_SHA
    - docker push $CI_IMAGE_NAMESPACE/my-db:latest

build_django_image:
  stage: build
  script:
    - docker build -t my-app:$CI_COMMIT_SHORT_SHA .
    - docker tag my-app:$CI_COMMIT_SHORT_SHA my-app:latest
    - docker images


push_mysql_image:
  stage: push
  script:
    - docker images
    - echo "Pushing MySQL image to Dockerhub"

push_django_image:
  stage: push
  script:
    - docker images
    - echo "Pushing Django image to Dockerhub"






# # push_image:
# #   stage: push
# #   image: docker:latest
# #   services:
# #     - docker:dind
# #   script:
# #     - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
# #     - export CI_REGISTRY_IMAGE=index.docker.io/georgikh/test_image
# #     - export CI_COMMIT_REF_SLUG="latest"
# #     - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
# #   only:
# #     - main

