stages:
  - build
  - push
  - deploy

image: docker:latest

services:
  - docker:dind

build_mysql_image:
  stage: build
  script:
    - docker build -t my-db:$CI_COMMIT_SHORT_SHA ./db/
    - docker save my-db:$CI_COMMIT_SHORT_SHA > my_db_$CI_COMMIT_SHORT_SHA.tar.gz
  artifacts:
    expire_in: 1h
    paths:
      - my_db_$CI_COMMIT_SHORT_SHA.tar.gz


build_django_image:
  stage: build
  script:
    - docker build -t my-app:$CI_COMMIT_SHORT_SHA .
    - docker save my-app:$CI_COMMIT_SHORT_SHA > my-app_$CI_COMMIT_SHORT_SHA.tar.gz
  
  artifacts:
    expire_in: 1h
    paths:
      - my-app_$CI_COMMIT_SHORT_SHA.tar.gz



push_mysql_image:
  stage: push
  script:
    - ls -la
    # - export CI_IMAGE_NAMESPACE=georgiheroco
    # - docker login -u $CI_USER -p $CI_PASSWORD $CI_HOST

    # - docker images
    # - echo "Pushing MySQL image to Dockerhub"

    
  dependencies:
    - build_mysql_image

# push_django_image:
#   stage: push
#   script:
#     - docker images
#     - echo "Pushing Django image to Dockerhub"






# # push_image:
# #   stage: push
# #   image: docker:latest
# #   services:
# #     - docker:dind
# #   script:
# #     - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
# #     - export CI_REGISTRY_IMAGE=index.docker.io/georgikh/test_image
# #     - export CI_COMMIT_REF_SLUG="latest"
# #     - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
# #   only:
# #     - main

