stages:
  - build
  - push
  - deploy

image: docker:latest

services:
  - docker:dind

build_mysql_image:
  stage: build
  script:
    - docker build -t my_db:$CI_COMMIT_SHORT_SHA ./db/
    - docker save my_db:$CI_COMMIT_SHORT_SHA > my_db_$CI_COMMIT_SHORT_SHA.tar.gz
  artifacts:
    expire_in: 1h
    paths:
      - my_db_$CI_COMMIT_SHORT_SHA.tar.gz


build_django_image:
  stage: build
  script:
    - docker build -t my-app:$CI_COMMIT_SHORT_SHA .
    - docker save my-app:$CI_COMMIT_SHORT_SHA > my-app_$CI_COMMIT_SHORT_SHA.tar.gz
  
  artifacts:
    expire_in: 1h
    paths:
      - my-app_$CI_COMMIT_SHORT_SHA.tar.gz



push_mysql_image:
  stage: push
  script:
    - echo "Login to DockerHub"
    - docker login -u $CI_USER -p $CI_PASSWORD $CI_HOST_URL

    - export CI_REGISTRY_NAMESPACE=georgiheroco
    - echo "Loading MySQL image from artifact"
    - docker load < my_db_$CI_COMMIT_SHORT_SHA.tar.gz
    - docker images

    - docker tag my_db:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_NAMESPACE/my_db:$CI_COMMIT_SHORT_SHA
    - docker tag my_db:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_NAMESPACE/my_db:latest
    
    - echo "Pushing MySQL image to Dockerhub"
    - docker push $CI_REGISTRY_NAMESPACE/my_db:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_NAMESPACE/my_db:latest
    
  dependencies:
    - build_mysql_image

push_django_image:
  stage: push

    
  script:
    - echo "Login to DockerHub"
    - docker login -u $CI_USER -p $CI_PASSWORD $CI_HOST_URL

    - export CI_REGISTRY_NAMESPACE=georgiheroco
    - echo "Loading django image from artifact"
    - docker load < my-app_$CI_COMMIT_SHORT_SHA.tar.gz
    - docker images

    - docker tag my-app:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_NAMESPACE/my-app:$CI_COMMIT_SHORT_SHA
    - docker tag my-app:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_NAMESPACE/my-app:latest
    
    - echo "Pushing Django image to Dockerhub"
    - docker push $CI_REGISTRY_NAMESPACE/my-app:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_NAMESPACE/my-app:latest

  dependencies:
    - build_django_image






# # push_image:
# #   stage: push
# #   image: docker:latest
# #   services:
# #     - docker:dind
# #   script:
# #     - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
# #     - export CI_REGISTRY_IMAGE=index.docker.io/georgikh/test_image
# #     - export CI_COMMIT_REF_SLUG="latest"
# #     - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
# #   only:
# #     - main

